apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spiderfoot-pvc
  namespace: scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: csi-s3
