apiVersion: v1
kind: Service
metadata:
  annotations: []
  labels: []
  name: spiderfoot
  namespace: scanner
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  selector:
    app: spiderfoot